force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Days_to_Conversion_Credit_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Conversion_Credit_Expiration__c</fullName>
    <formula>Conversion_Credit_Expiration_Date__c - Today()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to Conversion Credit Expiration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/ContextId__c.field-meta.xml
<CustomField>
    <fullName>ContextId__c</fullName>
    <label>ContextId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/ContextRecordId__c.field-meta.xml
<CustomField>
    <fullName>ContextRecordId__c</fullName>
    <label>ContextRecordId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Tactical_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Priority__c</fullName>
    <label>Tactical Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesTacticalPlan__c/SalesTacticalPlan__c.object-meta.xml
<CustomObject>
    <label>TeamSalesTacticalPlan</label>
    <nameField>
        <label>SalesTacticalPlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesTacticalPlans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTacticalPlan__c/fields/Tactical_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Ordering__c</fullName>
    <description>This is used to populate the dual list box in the management flow. It generally shouldn&#39;t be edited outside of that dual list box.</description>
    <label>Tactical_Ordering</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessPolicyTactics.cls
public with sharing class ProcessPolicyTactics {
    
    public static List<Policy__c> Process ( String tacticName, SalesTacticalPlan__c curSalesTacticalPlan, Integer maxResults) {
        List<SObject> relevantPolicies = new List<SObject>();
        switch on tacticName {
            when 'Policy Expiring Soon (Attained Age)'  {
                System.debug('entering Term Policy Expiring Soon');
                if (curSalesTacticalPlan.Tactical_Ordering__c.split(',').contains('Policy Expiring Soon (Attained Age)')) {
                    System.debug('Policy Expiring Soon (Attained Age) is a chosen tactic');
                    relevantPolicies = [select name, Id from Policy__c WHERE Policy__c.Days_to_Conversion_Credit_Expiration__c < 100 ORDER BY Policy__c.Days_to_Conversion_Credit_Expiration__c ASC  LIMIT :maxResults];
                }
            }
            when 'Conversion Option Expiring Soon'  {
                if (curSalesTacticalPlan.Tactical_Ordering__c.split(',').contains('Conversion Option Expiring Soon')) {
                    
                    System.debug('Conversion Option Expiring Soon is a chosen tactic');
                    relevantPolicies = [select name, Id from Policy__c WHERE Policy__c.Days_to_Conversion_Credit_Expiration__c	<100 AND Policy__c.Days_to_Conversion_Credit_Expiration__c >0 ORDER BY Policy__c.Days_to_Conversion_Credit_Expiration__c ASC  LIMIT :maxResults];
                }
            

            }
            when else {
                System.debug('unsupported value was passed in as tacticName');
            }
        }
        System.debug('Relevant Policies: ' + relevantPolicies);
        return relevantPolicies;
    }

    public static List<Recommendation> GenerateRecommendations (List<Policy__c> relevantPolicies, String tacticName, SalesTacticalPlan__c curSalesTacticalPlan ) {
        List<Recommendation> recs = new List<Recommendation>(); 
        if (relevantPolicies != null)
            for (Policy__c curItem:relevantPolicies) {
                Recommendation rec = new Recommendation(
                    Name = curItem.Name,
                    Description = 'Work on the ' + curItem.Name + ' Policy.' ,
                    //Pre-req: Create a screen flow with the name simpleFlow                        
                    ActionReference = 'TacticalFollowup',
                    AcceptanceLabel = 'Go',
                    Tactical_Priority__c = GenerateSalesTacticalPriorities.getPriority(curSalesTacticalPlan.Tactical_Ordering__c, tacticName),
                    ContextRecordId__c = curItem.Id,
                    ContextId__c = curItem.Id
                );
                System.debug('generated recommendation: ' + rec);
                System.debug('contextrecordId is ' + rec.ContextRecordId__c);
                recs.add(rec);
            }
        return recs;
    }
}