force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>East Asia</fullName>
            </value>
            <value>
                <fullName>Western Asia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Days_Closed__c.field-meta.xml
<CustomField>
    <fullName>Days_Closed__c</fullName>
    <formula>TODAY() - DATEVALUE(ClosedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Closed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Complete__c.field-meta.xml
<CustomField>
    <fullName>Followup_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup Complete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Days_to_Conversion_Credit_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Days_to_Conversion_Credit_Expiration__c</fullName>
    <formula>Conversion_Credit_Expiration_Date__c - Today()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to Conversion Credit Expiration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/ContextId__c.field-meta.xml
<CustomField>
    <fullName>ContextId__c</fullName>
    <label>ContextId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/ContextRecordId__c.field-meta.xml
<CustomField>
    <fullName>ContextRecordId__c</fullName>
    <label>ContextRecordId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Tactical_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Priority__c</fullName>
    <label>Tactical Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesTacticalPlan__c/SalesTacticalPlan__c.object-meta.xml
<CustomObject>
    <label>TeamSalesTacticalPlan</label>
    <nameField>
        <label>SalesTacticalPlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesTacticalPlans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTacticalPlan__c/fields/Tactical_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Ordering__c</fullName>
    <description>This is used to populate the dual list box in the management flow. It generally shouldn&#39;t be edited outside of that dual list box.</description>
    <label>Tactical_Ordering</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessServiceTactics.cls
public with sharing class ProcessServiceTactics {
    
    public static List<SObject> Process (String tacticName, SalesTacticalPlan__c curTacticalPlan, Integer maxResults) {
        List<SObject> relevantRecords = new List<SObject>();

        switch on tacticName {
            when 'Limited Offers'  {
                System.debug('entering Limited Offers');
                if (curTacticalPlan.Tactical_Ordering__c.split(',').contains('Limited Offers')) {
                    System.debug('Limited Offers is a chosen tactic');
                    //travel sector affected by an epidemic. highly disruptive. ask if we can help. HQ has authoized payment relief of 30 days
                    relevantRecords = [select Name, Id from Account WHERE Account.Industry IN ('Transportation','Tourism') AND Account.Region__c = 'East Asia'  LIMIT :maxResults];
                    for(SObject curItem : relevantRecords){
                        curItem.put('Description','Travel sector affected by an epidemic. May be disruptive to this customer. HQ has authorized payment relief of 30 days');
                    }
                }
            }
            when 'Case Follow Up'  {
                if (curTacticalPlan.Tactical_Ordering__c.split(',').contains('Case Follow Up')) {
                    //find cases where close date is less than 7 days ago, followup complete is false, tier is premium, and owner is cur user
                    System.debug('Case Follow Up is a chosen tactic');

                    relevantRecords = [select Subject, Id from Case WHERE Days_Closed__c < 7 AND Followup_Complete__c = false LIMIT :maxResults];
                    System.debug('Relevant Records: ' + relevantRecords);
                    for(SObject curItem : relevantRecords){
                        curItem.put('Description','Case recently closed and not followed up');
                        //curItem.put('Subject', curItem.get('Subject'));
                    }
                }
            }
            when 'Priority Messages'  {
                if (curTacticalPlan.Tactical_Ordering__c.split(',').contains('Priority Messages')) {
                    
                    System.debug('Priority Messages is a chosen tactic');
                   // relevantAccounts = [select name, Id from Policy__c WHERE Policy__c.Days_to_Conversion_Credit_Expiration__c	<100 AND Policy__c.Days_to_Conversion_Credit_Expiration__c >0 ORDER BY Policy__c.Days_to_Conversion_Credit_Expiration__c ASC  LIMIT :maxResults];
                }
            }
            when 'Einstein (Renewal Risks)'  {
                if (curTacticalPlan.Tactical_Ordering__c.split(',').contains('Einstein (Renewal Risks)')) {
                    
                    System.debug('Einstein (Renewal Risks) is a chosen tactic');
                   // relevantAccounts = [select name, Id from Policy__c WHERE Policy__c.Days_to_Conversion_Credit_Expiration__c	<100 AND Policy__c.Days_to_Conversion_Credit_Expiration__c >0 ORDER BY Policy__c.Days_to_Conversion_Credit_Expiration__c ASC  LIMIT :maxResults];
                }
            }
            when else {
                System.debug('unsupported value was passed in as tacticName');
            }
        }
        System.debug('Relevant Records: ' + relevantRecords);
        return relevantRecords;
    }

    public static List<Recommendation> GenerateRecommendations (List<SObject> relevantRecords, String tacticName, SalesTacticalPlan__c curTacticalPlan ) {
        List<Recommendation> recs = new List<Recommendation>(); 
        String curName;

        if (relevantRecords != null)
            for (SObject curItem : relevantRecords) {
                if (curItem.getSObjectType().getDescribe().getName() != 'Case' ) {
                    curName = (String)curItem.get('Name');
                }
                else {
                    curName = (String)curItem.get('Subject');
                }
                Recommendation rec = new Recommendation(
                    Name = curName,
                    Description = 'Prioritize ' + curName + '. \n The reason is: ' + (String)curItem.get('Description') ,
                    //Pre-req: Create a screen flow with the name simpleFlow                        
                    ActionReference = 'TacticalFollowup',
                    AcceptanceLabel = 'Go',
                    Tactical_Priority__c = GenerateSalesTacticalPriorities.getPriority(curTacticalPlan.Tactical_Ordering__c, tacticName),
                    ContextRecordId__c = (String)curItem.Id,
                    ContextId__c = (String)curItem.Id
                );
                System.debug('generated recommendation: ' + rec);
                System.debug('contextrecordId is ' + rec.ContextRecordId__c);
                recs.add(rec);
            }
        return recs;
    }
}