force-app/main/default/objects/Opportunity/fields/Days_To_Close__c.field-meta.xml
<CustomField>
    <fullName>Days_To_Close__c</fullName>
    <formula>CloseDate - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days To Close</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Einstein_Score__c.field-meta.xml
<CustomField>
    <fullName>Einstein_Score__c</fullName>
    <label>Einstein Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Midline</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommendation/fields/Tactical_Priority__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Priority__c</fullName>
    <label>Tactical Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesTacticalPlan__c/SalesTacticalPlan__c.object-meta.xml
<CustomObject>
    <label>TeamSalesTacticalPlan</label>
    <nameField>
        <label>SalesTacticalPlan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesTacticalPlans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesTacticalPlan__c/fields/Sector_Name__c.field-meta.xml
<CustomField>
    <fullName>Sector_Name__c</fullName>
    <label>Sector Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sector</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesTacticalPlan__c/fields/Tactical_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Tactical_Ordering__c</fullName>
    <description>This is used to populate the dual list box in the management flow. It generally shouldn&#39;t be edited outside of that dual list box.</description>
    <label>Tactical_Ordering</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Sector.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>Midline</fullName>
    </customValue>
    <customValue>
        <fullName>Small</fullName>
    </customValue>
    <masterLabel>Sector</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateSalesTacticalPriorities.cls
public with sharing class GenerateSalesTacticalPriorities {


    @InvocableMethod
    public static List<List<Recommendation>> Generate(List<Requests> requests) {
        String userId = requests[0].userId;
        Integer maxResults = requests[0].maxResults;
        String salesTacticalPlanName = requests[0].salesTacticalPlanName;
        String tacticName = requests[0].tacticName;
        System.debug('entering Generate Sales TacticalPriorities');
        System.debug('cur values are: ' +tacticName + ' ' + maxResults + ' ' + userId);
        //1) read in the SalesPriorityPlan
        //2) Find all opportunities where the criteria type’s value exceeds the threshold
        //3) Generate recommendations  (unless the value of the criteria is 0) and set the TacticalPriority

        SalesTacticalPlan__c curSalesTacticalPlan = [select name, Id,Sector_Name__c, Tactical_Ordering__c,Minimum_Opportunity_Value__c	,Minimum_Score__c	 from SalesTacticalPlan__c where name = :salesTacticalPlanName];
        System.debug('returned tactical plan is: ' + curSalesTacticalPlan);
        List<Opportunity> relevantOpportunities;

        switch on tacticName {
            when 'Einstein Score'  {
                System.debug('entering Einstein Score');
                if (curSalesTacticalPlan.Tactical_Ordering__c.split(',').contains('Einstein Score')) {
                    System.debug('Einstein Score is a chosen tactic');
                    relevantOpportunities = [select name, Id from Opportunity WHERE Opportunity.Einstein_Score__c != null ORDER BY Opportunity.Einstein_Score__c DESC  LIMIT :maxResults];
                }
            }
            when 'Opportunity Value'  {
                if (curSalesTacticalPlan.Tactical_Ordering__c.split(',').contains('Opportunity Value')) {
                    System.debug('Opportunity is a chosen tactic');
                    relevantOpportunities = [select name, Id from Opportunity WHERE Opportunity.Amount != null ORDER BY Opportunity.Amount DESC  LIMIT :maxResults];
                }
            }
            when 'Proximity to Renewal'  {
                if (curSalesTacticalPlan.Tactical_Ordering__c.split(',').contains('Proximity to Renewal')) {
                    System.debug('Proximity to Renewal is a chosen tactic');
                    //query for opps with the shortest time to CloseDate, limited by the max requested
                    relevantOpportunities = [select name, Id from Opportunity WHERE Opportunity.Days_To_Close__c != null ORDER BY Opportunity.Days_To_Close__c ASC NULLS LAST LIMIT :maxResults];
                }
            }
            when 'Sector Focus'  {
                System.debug('Sector Focus is a chosen tactic');
                List<String> curTactics = curSalesTacticalPlan.Tactical_Ordering__c.split(',');
                if (curTactics.contains('Sector Priority')) {
                    System.debug('ordering contains Sector priority');
                    relevantOpportunities = [select name, Id from Opportunity where Sector__c = :curSalesTacticalPlan.Sector_Name__c LIMIT :maxResults];
                }

            }
            when else {
                System.debug('unsupported value was passed in as tacticName');
            }
        }
        System.debug('relevantOpportunities are: ' + relevantOpportunities);
            
        List<Recommendation> recs = new List<Recommendation>(); 
        if (relevantOpportunities != null)
            for (Opportunity curOpp:relevantOpportunities) {
                Recommendation rec = new Recommendation(
                    Name = curOpp.Name,
                    Description = 'Work on the ' + curOpp.Name + ' opportunity.' ,
                    //Pre-req: Create a screen flow with the name simpleFlow                        
                    ActionReference = 'TacticalFollowup',
                    AcceptanceLabel = 'Go',
                    Tactical_Priority__c = getPriority(curSalesTacticalPlan.Tactical_Ordering__c, tacticName)
                );
                System.debug('generated recommendation: ' + rec);
                recs.add(rec);
            }

              //Create a Results object to hold the return values
        List<List<Recommendation>> response = new List<List<Recommendation>>();


        //add the return values to the Results object
        response.add(recs);
        System.debug('response is: '+ response);
        return response; 

    }

    //the dual list box works with comma-separated strings. locate the priority of the current tactic
    public static Integer getPriority(String orderingString, String tacticName) {
        //break the string into an array
        //find the name in the array
        //return the index+1. return 0 if not found
        List<String> orderedTactics = orderingString.split(',');
        Integer index = orderedTactics.indexOf(tacticName);
        return index+1;

    }


    public class InvocableActionException extends Exception {
    }


    public class Requests {

        @InvocableVariable
        public String userId;

        @InvocableVariable
        public String tacticName;

        @InvocableVariable
        public String salesTacticalPlanName;

        @InvocableVariable
        public Integer maxResults;
    }

    public class Results {

        @InvocableVariable
        public List<List<Recommendation>> curRecs;

    }

}